# Generated by Django 5.1.15 on 2026-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_clinica_email_clinica_endereco_clinica_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GESTOR', 'Gestor'), ('SECRETARIA', 'Secretária'), ('MEDICO', 'Médico')], default='MEDICO', max_length=20),
        ),
    ]
