# Generated by Django 5.1.15 on 2026-05-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origens', to='clinicas.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('salvar_contato', models.BooleanField(default=False)),
                ('origem_manual', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clinicas.clinica')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.origem')),
            ],
        ),
    ]
