# Generated by Django 5.1.15 on 2026-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='compareceu',
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('COMPARECEU', 'Compareceu'), ('FALTOU', 'Faltou')], default='AGENDADO', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
    ]
