# Generated by Django 5.1.15 on 2026-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='fup1_feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fup2_feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fup3_feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='fup4_feito',
            field=models.BooleanField(default=False),
        ),
    ]
