# Generated by Django 5.1.15 on 2026-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='ciclica',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_lembrete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipo_repeticao',
            field=models.CharField(choices=[('PONTUAL', 'Pontual / Lembrete'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], default='PONTUAL', max_length=20),
        ),
    ]
