# Generated by Django 5.1.15 on 2026-05-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
        ('leads', '0007_remove_tarefa_ciclica_tarefa_data_lembrete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='NOVO', max_length=50),
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('color', models.CharField(default='bg-indigo-50 border-indigo-200 text-indigo-700', max_length=100)),
                ('ordenacao', models.IntegerField(default=0)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_columns', to='clinicas.clinica')),
            ],
        ),
    ]
