# Generated by Django 5.1.15 on 2026-05-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_alter_customuser_role'),
        ('leads', '0009_lead_data_primeiro_contato_lead_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='compareceu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='clinicas.clinica')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.interesse'),
        ),
    ]
