# Generated by Django 5.1.15 on 2026-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_compareceu_interesse_lead_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_lembrete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='resolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
