# Generated by Django 5.1.15 on 2026-05-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_consulta_data_lembrete_consulta_resolvido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='resultado_fup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
