# Generated by Django 5.1.15 on 2026-05-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_resultado_fup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pos_fup1_feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='pos_fup2_feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='pos_fup3_feito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='resultado_pos_fup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
