# Generated by Django 5.1.15 on 2026-05-15 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_alter_customuser_role'),
        ('leads', '0013_lead_pos_fup1_feito_lead_pos_fup2_feito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=255)),
                ('assunto', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacoes', to='clinicas.clinica')),
            ],
        ),
    ]
