# Generated by Django 5.1.15 on 2026-05-15 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_alter_customuser_role'),
        ('leads', '0014_orientacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientacao',
            name='assunto_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AssuntoOrientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos_orientacao', to='clinicas.clinica')),
            ],
        ),
        migrations.AlterField(
            model_name='orientacao',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientacoes', to='leads.assuntoorientacao'),
        ),
    ]
