# Generated by Django 5.1.15 on 2026-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_orientacao_assunto_texto_assuntoorientacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interesse_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
